
; Set BAR0 Base Address
packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 0
	FirstDwBe=0xF
	Register=PCIE_CFGS_BAR0_REG_ADDR
	Payload=(0xffffffff)
}

wait =TLP 
{
    TLPType=Cpl
    Tag = LAST_CFG_TAG
}

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 1
	FirstDwBe=0xF
	Register=PCIE_CFGS_BAR0_REG_ADDR
}

wait =TLP 
{
    TLPType=CplD
    Tag = LAST_CFG_TAG
}



packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 0
	FirstDwBe=0xF
	Register=PCIE_CFGS_BAR0_REG_ADDR
	Payload=(PCIE_CFGS_BAR0_REG_VAL)
}

wait =TLP 
{
    TLPType=Cpl
    Tag = LAST_CFG_TAG
}

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 1
	FirstDwBe=0xF
	Register=PCIE_CFGS_BAR0_REG_ADDR
}

wait =TLP 
{
    TLPType=CplD
    Tag = LAST_CFG_TAG
}

; Set EROM Base Address
packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 5
	FirstDwBe=0xF
	Register=PCIE_CFGS_EROM_REG_ADDR
}

wait =TLP 
{
    TLPType=CplD
    Tag = LAST_CFG_TAG
}


packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 4
	FirstDwBe=0xF
	Register=PCIE_CFGS_EROM_REG_ADDR
	Payload=(PCIE_CFGS_EROM_REG_VAL)
}

wait =TLP 
{
    TLPType=Cpl
    Tag = LAST_CFG_TAG
}

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 5
	FirstDwBe=0xF
	Register=PCIE_CFGS_EROM_REG_ADDR
}

wait =TLP 
{
    TLPType=CplD
    Tag = LAST_CFG_TAG
}

;-------------------------------------------------------------------------------------------------------------

; enable MSI capability
/*  
packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 7
	FirstDwBe=0xF
	Register=PCIE_CFGS_MSICAP_REG_ADDR
}

wait =TLP 
{
    TLPType=CplD
    Tag = 7
}

packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 6
	FirstDwBe=0xF
	Register=PCIE_CFGS_MSICAP_REG_ADDR
	Payload=(PCIE_CFGS_MSICAP_REG_VAL)
}

wait =TLP 
{
    TLPType=Cpl
    Tag = 6
}

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 7
	FirstDwBe=0xF
	Register=PCIE_CFGS_MSICAP_REG_ADDR
}

wait =TLP 
{
    TLPType=CplD
    Tag = 7
}
*/
;---------------------------------------------------------------------------------
; Enable Memory Address space

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 9
	FirstDwBe=0x1
	Register=PCIE_PCFG_STTCMD
}

wait =TLP 
{
    TLPType=CplD
    Tag = 9
}

packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 8
	FirstDwBe=0x1
	Register=PCIE_PCFG_STTCMD
	Payload=(PCIE_CFGS_CMD_REG_VAL)
}

wait =TLP 
{
    TLPType=Cpl
    Tag = 8
}

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 9
	FirstDwBe=0x1
	Register=PCIE_PCFG_STTCMD
}

wait =TLP 
{
    TLPType=CplD
    Tag = 9
}

;-------------------------------------------------------------------

; Set PCIE max payload sizes to maximum

; reading the maxpayload bit[2:0] 
packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 1
	FirstDwBe=0xF
	Register=PCI_Express_Device_Capabilities_Register
}

wait =TLP 
{
    TLPType=CplD
    Tag = 1
}

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 1
	FirstDwBe=0xF
	Register=PCI_Express_Device_Control_and_Status_Register
}

wait =TLP 
{
    TLPType=CplD
    Tag = 1
}


packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 0
	FirstDwBe=0xF
	Register=PCI_Express_Device_Control_and_Status_Register
	Payload=(PCIE_CFGS_EXPDEVSTTCTL_REG_VAL)
}

wait =TLP 
{
    TLPType=Cpl
    Tag = 0
}

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 1
	FirstDwBe=0xF
	Register=PCI_Express_Device_Control_and_Status_Register
}

wait =TLP 
{
    TLPType=CplD
    Tag = 1
}
;---------------------------------------------------------------------------------------------

; disable the MSI and enable the MSI-X 

; disable msi
/*
packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 7
	FirstDwBe=0xF
	Register=PCIE_CFGS_MSICAP_REG_ADDR
}

wait =TLP 
{
    TLPType=CplD
    Tag = 7
}

packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 6
	FirstDwBe=0xF
	Register=PCIE_CFGS_MSICAP_REG_ADDR
	Payload=(0x00000000)
}

wait =TLP 
{
    TLPType=Cpl
    Tag = 6
}

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 7
	FirstDwBe=0xF
	Register=PCIE_CFGS_MSICAP_REG_ADDR
}

wait =TLP 
{
    TLPType=CplD
    Tag = 7
}
*/
; Enable MSI-X-bit[31]
; reading MSIX-adress_offset [26:16]

/*
packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 7
	FirstDwBe=0xF
	Register=MSIX_Control_Register
}

wait =TLP 
{
    TLPType=CplD
    Tag = 7
}


packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 2
	FirstDwBe=0xF
	Register=MSIX_Control_Register
	Payload=(0x11c00081)
}

wait=TLP
{
    TLPType = Cpl
    Tag = 2
}
*/

packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 7
	FirstDwBe=0xF
	Register=PCI_Express_Device_Control_and_Status_Register_2		; #Device Status 2 | Device Control 2
}

wait =TLP 
{
    TLPType=CplD
    Tag = 7
}


packet = TLP {
	TLPType=CfgWr0
	Length=1
    Tag = 2
	FirstDwBe=0xF
	Register=PCI_Express_Device_Control_and_Status_Register_2	; #Device Status 2 | Device Control 2
	Payload=(0x00040000)							; Enable LTR
}


wait=TLP
{
    TLPType = Cpl
    Tag = 2
}


packet = TLP {
	TLPType = CfgRd0
	Length=1
    Tag = 7
	FirstDwBe=0xF
	Register=PCI_Express_Device_Control_and_Status_Register_2
}

wait =TLP 
{
    TLPType=CplD
    Tag = 7
}

;-----------------------------------------------------------------

; Read Capabilites Pointer to find extended capabilities
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=8
	FirstDwBe=0x0F
	Register=PCIE_CAPABILITIES_PTR
	StoreData = ( FROM_MEM64, 0 )
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}

; Read Next Extended Capability
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=2
	FirstDwBe=0x0F
	Register=PCI_Power_Magament_Cap
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}

; Read Next Extended Capability
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=3
	FirstDwBe=0x0F
	Register=PCI_Express_Capability
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}

; Read Next Extended Capability
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=4
	FirstDwBe=0x0F
	Register=MSI_X_CAPABILITY_ADDRESS
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}

; Read Next Extended Capability
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=5
	FirstDwBe=0x0F
	Register=PCI_Express_Capability
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}

; Read Link_Control_and_Status_Register
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=6
	FirstDwBe=0x0F
	Register=Link_Control_and_Status_Register
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}

; Read L1_PM_Substates_Capabilities_Header
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=7
	FirstDwBe=0x0F
	Register=L1_PM_Substates_Capabilities_Header
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}

; Read L1_PM_Substates_Capabilities_Register
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=8
	FirstDwBe=0x0F
	Register=L1_PM_Substates_Capabilities_Register
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}

; L1_PM_Substates_Control_1_Register
packet = TLP {
	TLPType = CfgRd0
	Length=1
	Tag=9
	FirstDwBe=0x0F
	Register=L1_PM_Substates_Control_1_Register
}

wait =TLP 
{
    TLPType=CplD
    Tag=LAST_CFG_TAG
}