; Title: trainerinit.peg
; Description: Trainer initialization script
; Author: Madhur Jain
; Date: 01/30/2018

/* Initiate Trainer reset */
Config=General 
{
    TrainerReset = Yes
}

include="linkdown.peg"

; Admin Commands
AddressSpace=Write
{
	Location = Mem64
	Offset = 0x0	; Start address for admin queue
	Size = 0x480	; 18 commands (Idfy, Set Num Queue, 8 Queues) * 64 bytes per command
	LoadFrom = "dump_idfyctrlr_create_8_queue.bin"
}

; IO Commands - 1024 Writes
AddressSpace=Write
{
	Location = Mem64
	Offset = 0x2000	; Start address for Queue 1
	Size = 0x10000	; 1024 commands * 64 bytes per command
	LoadFrom = "write10k_queue1_128g_pingpongpattern.bin"
}