; Title: gen2_check.peg
; Description: Trainer script to check Gen 2 compatibility
; Author: Madhur Jain
; Date: 03/02/2018

/* Initiate Trainer reset */

;Link=PERST_Assert

;Config=General 
;{
;    TrainerReset = Yes
;}

include="Common_Files\linkup_gen2.peg"
include="Common_Files\ex_scripts_defs.peg"
include="Common_Files\pcfgs_init.peg"

include="Common_Files\pciewritemsixtable.peg"

include="Common_Files\pciereadmsixtable.peg"

include="Common_Files\nvme_init.peg"
include="Common_Files\nvme_admin_cmd_idenitfy_controller.peg"
Config=Definitions
{
	NUM_IO_QUEUES = 0x01
}
include="Common_Files\nvme_create_queues.peg"
include="Common_Files\nvme_read.peg"
;include="Common_Files\nvme_set_feature.peg"
include="Common_Files\nvme_shutdown.peg"
include="Common_Files\linkdown.peg"

