; Title: power-on-ready-typical.peg
; Description: Trainer script to measure typical power on ready time for ipa in ps0
; Author: Srinath P
; Date: 03/05/2019

include="Common_Files\linkup_gen3.peg"
include="Common_Files\ex_scripts_defs.peg"
include="Common_Files\pcfgs_init.peg"
include="Common_Files\pciemsixtable.peg"

include="Common_Files\nvme_init.peg"
include="Common_Files\nvme_admin_cmd_idenitfy_controller.peg"
Config=Definitions
{
	NUM_IO_QUEUES = 0x01
    powerstate = 0
}
include="Common_Files\nvme_create_queues.peg"
include="Common_Files\nvme_set_feature_ps.peg"
include="Common_Files\nvme_read.peg"

include="Common_Files\nvme_shutdown.peg"
include="Common_Files\linkdown.peg"

