; Title: smart.peg
; Description: Trainer script to run, shn -> linkdown -> power cycle test sequence and check for ugsd / gsd counts 
; Author: Muhammad Khan
; Date: 10/23/2019

/* Initiate Trainer reset */

;Link=PERST_Assert

;Config=General 
;{
;    TrainerReset = Yes
;}

include="Common_Files\linkup_gen3.peg"
include="Common_Files\ex_scripts_defs.peg"
include="Common_Files\pcfgs_init.peg"
include="Common_Files\pciemsixtable.peg"

include="Common_Files\nvme_init.peg"
include="Common_Files\nvme_admin_cmd_idenitfy_controller.peg"
Config=Definitions
{
	NUM_IO_QUEUES = 0x01
}
;include="Common_Files\nvme_create_queues.peg"
;include="Common_Files\nvme_read.peg"

/*
AddressSpace=Read 
{
    Location=Mem64
    Offset = 0
    Size =   0x480			; 18 commands (Idfy, Set Num Queues, 8 Queues) * 64 bytes per command
    SaveTo = "BIN_FILES\Dump_IdfyCtrlr_Create_8_Queue.bin"
}

AddressSpace=Read 
{
    Location=Mem64
    Offset = HOST_NVM_CMDS_SQ1
    Size =   0x40			; 1 command * 64 bytes per command
    SaveTo = "BIN_FILES\Dump_4K_Read.bin"
}
*/

/* GET SMART REPORT */

Structure=NVMe 
{
    Location=Mem64
    Offset = 0x40
    NVMeStructType=AdminCommand
    OpcodeAdmin = ADMIN_GET_LOG_PAGE
    CID = 1
    PRP1_Low = 0x3F25B190
    PRP1_High = 0x8
    PRP2_Low = 0x3F25C000
    PRP2_High = 0x8
    LogPageID = SMART_Health
    NumLogDWs = 39
}

; Write Admin doorbell
Packet=TLP 
{
    TLPType=MWr32
    Length = 1
    LastDwBe = 0x0
    FirstDwBe = 0xF
    Address = ( HIM_BAR0_REGS_BASE_ADDR + 0x1000 )
    Payload = ( 02000000 )     
}
wait=TLP
{
    TLPType = MWr32
    Address = 0xFEE0100C
}

; Write Admin Completion Queue Head
Packet=TLP 
{
    TLPType=MWr32
    Length = 1
    LastDwBe = 0x0
    FirstDwBe = 0xF
    Address = ( HIM_BAR0_REGS_BASE_ADDR + 0x1004 )
    Payload = ( 02000000 )   
}

; Issuing nvme shutdown notification + linkdown
include="Common_Files\nvme_shutdown.peg"
wait=500000
Link=Disabled

; Write texting file "power_cycle.txt" to trigger polling agent to execute GPIO for power cycle
AddressSpace=Read 
{
    Location=Mem32A
    SaveTo = "C:\SanDisk\Executable\AutoLatency\power_cycle.txt"
}

; 3 second delay for pwrcycle 
wait=3000000000

; Second training sequence 

include="Common_Files\linkup_gen3.peg"
include="Common_Files\pcfgs_init.peg"
include="Common_Files\pciemsixtable.peg"

include="Common_Files\nvme_init.peg"
include="Common_Files\nvme_admin_cmd_idenitfy_controller.peg"
Config=Definitions
{
	NUM_IO_QUEUES = 0x01
}
;include="Common_Files\nvme_create_queues.peg"
;include="Common_Files\nvme_read.peg"

/*
AddressSpace=Read 
{
    Location=Mem64
    Offset = 0
    Size =   0x480			; 18 commands (Idfy, Set Num Queues, 8 Queues) * 64 bytes per command
    SaveTo = "BIN_FILES\Dump_IdfyCtrlr_Create_8_Queue.bin"
}

AddressSpace=Read 
{
    Location=Mem64
    Offset = HOST_NVM_CMDS_SQ1
    Size =   0x40			; 1 command * 64 bytes per command
    SaveTo = "BIN_FILES\Dump_4K_Read.bin"
}
*/

/* GET SMART REPORT */

Structure=NVMe 
{
    Location=Mem64
    Offset = 0x40
    NVMeStructType=AdminCommand
    OpcodeAdmin = ADMIN_GET_LOG_PAGE
    CID = 1
    PRP1_Low = 0x3F25B190
    PRP1_High = 0x8
    PRP2_Low = 0x3F25C000
    PRP2_High = 0x8
    LogPageID = SMART_Health
    NumLogDWs = 39
}

; Write Admin doorbell
Packet=TLP 
{
    TLPType=MWr32
    Length = 1
    LastDwBe = 0x0
    FirstDwBe = 0xF
    Address = ( HIM_BAR0_REGS_BASE_ADDR + 0x1000 )
    Payload = ( 02000000 )     
}
wait=TLP
{
    TLPType = MWr32
    Address = 0xFEE0100C
}

; Write Admin Completion Queue Head
Packet=TLP 
{
    TLPType=MWr32
    Length = 1
    LastDwBe = 0x0
    FirstDwBe = 0xF
    Address = ( HIM_BAR0_REGS_BASE_ADDR + 0x1004 )
    Payload = ( 02000000 )   
}

include="Common_Files\nvme_shutdown.peg"
include="Common_Files\linkdown.peg"