; Title: power-on-ready-typical.peg
; Description: Trainer script to measure typical power on ready time
; Author: Madhur Jain
; Date: 01/30/2018

/* Initiate Trainer reset */

;Link=PERST_Assert

;Config=General 
;{
;    TrainerReset = Yes
;}

include="linkup.peg"
include="ex_scripts_defs.peg"
include="pcfgs_init.peg"
include="pciemsixtable.peg"

include="nvme_init.peg"
include="nvme_admin_cmd_idenitfy_controller.peg"
Config=Definitions
{
	NUM_IO_QUEUES = 0x01
}
include="nvme_create_queues.peg"
include="nvme_read.peg"

/*
AddressSpace=Read 
{
    Location=Mem64
    Offset = 0
    Size =   0x480			; 18 commands (Idfy, Set Num Queues, 8 Queues) * 64 bytes per command
    SaveTo = "Dump_IdfyCtrlr_Create_8_Queue.bin"
}

AddressSpace=Read 
{
    Location=Mem64
    Offset = HOST_NVM_CMDS_SQ1
    Size =   0x40			; 1 command * 64 bytes per command
    SaveTo = "Dump_4K_Read.bin"
}
*/

include="nvme_shutdown.peg"
include="linkdown.peg"

