; reading the SHN status prior to init shutdown
Packet=TLP 
{
    TLPType=MRd64
    AddressHi = 0xffffffff
    AddressLo = HIM_BAR0_REGS_BASE_ADDR 
    NVMeControllerReg = CC_ControllerConfig
    StoreData = ( FROM_MEM64, HOST_SCRATCH_MEM )
}

Wait=TLP 
{
    TLPType=CplD
}

; Set CC.SHN to 01 (Normal Shutdown)
packet="Temp_OneDwordWrite"
{
    Tag = 1
    AddressHi = 0xffffffff  
    AddressLo = ( HIM_BAR0_REGS_BASE_ADDR + 0x14 )
    Payload = ( 01404600 )
}

; Poll CSTS.SHST to be 10
Loop=Begin

Packet=TLP 
{
    TLPType=MRd64
    AddressHi = 0xffffffff  
    AddressLo = HIM_BAR0_REGS_BASE_ADDR 
    NVMeControllerReg = CSTS_ControllerStatus
    StoreData = ( FROM_MEM64, HOST_SCRATCH_MEM )
}

Wait=TLP 
{
    TLPType=CplD
}

Loop=Break 
{
    Location = Mem64
    Offset = (HOST_SCRATCH_MEM);
    FieldSize = Dword
    Endian = Little
    FieldAction = MaskAND
    Mask = 0x0C
    Result = 0x08;
}

Loop=End
